version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - rate_limiter_network

  rate-limiter:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis:6379/0
      - IP_RATE_LIMIT=10
      - IP_RATE_WINDOW=1s
      - IP_BLOCK_TIME=5m
      - TOKEN_RATE_LIMIT=100
      - TOKEN_RATE_WINDOW=1s
      - TOKEN_BLOCK_TIME=5m
      # Example token configurations
      - TOKEN_abc123_LIMIT=50
      - TOKEN_abc123_WINDOW=1s
      - TOKEN_abc123_BLOCK_TIME=10m
      - TOKEN_vip_token_LIMIT=1000
      - TOKEN_vip_token_WINDOW=1s
      - TOKEN_vip_token_BLOCK_TIME=1m
    depends_on:
      - redis
    networks:
      - rate_limiter_network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  rate_limiter_network:
    driver: bridge